image: elixir:1.6

variables:
  MIX_ENV: "test"
  #MIX_TARGET: "rpi3"

stages:
  - test

before_script:
  #- apt-get -qq update && apt-get install -y ssh-askpass squashfs-tools git g++ libssl-dev libncurses5-dev bc m4 make unzip cmake python
  - mix local.hex --force
  - mix local.rebar --force
  #- mix archive.install hex nerves_bootstrap
  #- mix local.nerves
  - mix deps.get --only test

unit-testing:
  stage: test
  script:
    - mix test
    - coveralls